### ISSUE TITLE
You cannot unzip an archive if it contains folders with files

### ISSUE THREAD

**Issue by SergeantSergey** [nejckorasa/s3-stream-unzip#8]
When unzipping an archive in which there are packs with files or subfolders with files, I encounter the following error:
```
Failed initialising multipart upload with uploadId null
Aborting [S3MultipartUpload uploading to <folder>/, with uploadId null due to error: {}
com.amazonaws.services.s3.model.AmazonS3Exception: Object name contains unsupported characters. (Service: Amazon S3; Status Code: 400)
```

Can you please tell me if the library can unzip the archive if it contains folders?

**Comment by nejckorasa** [comment]
Hi, thanks for opening the ticket. It would really help if you could provide some more details in order to replicate the scenario:
- full setup of `S3UnzipManager` and how it's used
- folder structure you are trying to upload
- full stacktrace

Looking at the exception above, could it be that the object/folder path contains unsupported character? Please see here for the characters that are not supported: [AmazonS3 - Creating object key names](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html). Is `<folder>/` an actual object path or have you just redacted the path?

Uploading archives containing folders was admittedly never tested and there are no existing tests for that use case. Ideally we can replicate the scenario in a test, e.g. [S3UnzipManagerTest](https://github.com/nejckorasa/s3-stream-unzip/blob/440fadf676dc4ced56f81b7f98cff0dc86e39d1b/src/test/java/io/github/nejckorasa/s3/S3UnzipManagerTest.java#L17). 

I've written a quick test and it successfully uploads a folder - that is using mock s3 but so far it has proven to be quite representative to the real s3.

If you'd like, feel free to open a PR and test the scenario yourself - I'd really appreciate it! I can look into it in a couple of days.
